# Generated by Django 5.2.1 on 2025-08-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postagem_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='texto',
            field=models.CharField(max_length=2000),
        ),
    ]
